Revert "[shell-runtime] add timestamp pallet" It is not needed. The previous error upon upgrade: `panicked at Timestamp no inherent data provided.` Is a client error - not a runtime.
This reverts commit 460102a7